### PR TITLE
Add editor context menu (Undo, Redo, Cut, Copy, Paste).

### PR DESCRIPTION
**Pull request by GHSid**

### CODE REVIEW

**Comment by joseffallman** [comment]
Hello.
This is a great feature for TypeSQF editor. 

I would suggest that we add this in the MainWindow.xaml instead.
Wouldn't that be more simple when we want to add more to this menu, like "Go to definition" (F12 shortcut)
Perhaps the search/replace command also could be added?
`<MenuItem Command="Replace" />`

What does @XEngima think about that?

**Comment by GHSid** [comment]
Hello.
Thanks.

I've been waiting for a similar menu for a long time (as well as highlighting brackets - thank you for that). Unfortunately, I am not a C # programmer and it is difficult for me to understand the structure of the project, but I found a similar solution and finally decided to add this menu to the editor.
If you think it is correct to add this menu elsewhere in the project, then please do so (I allowed to make changes to the code that I added here).

**Comment by GHSid** [comment]
Changed the position of the code in the project and added the "Replace" command to the menu.

**Comment by GHSid** [comment]
@XEngima, @joseffallman , do you want to change something in this menu before the merge?

**Comment by XEngima** [comment]
Thanks GHSid for a great start with this context menu. But it's not complete (selecting an item does nothing). Do you plan to complete this? Otherwise I'll look more into it when I have the time.

**Comment by GHSid** [comment]
Hi, @XEngima !
Thanks. It seems to me that the menu items that I have implemented are working. Maybe I didn't understand the question? ([**https://youtu.be/VMqNklqXDFM**](https://youtu.be/VMqNklqXDFM)) Of course, if you ( @XEngima , @joseffallman  )want to add something to the menu - I just welcome it.

**Pull request merged**
